# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: download.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'download.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64ownload.proto\x12\x04grpc\"M\n\x0f\x44ownloadRequest\x12\x11\n\tsong_name\x18\x01 \x01(\t\x12\x13\n\x0b\x61rtist_name\x18\x02 \x01(\t\x12\x12\n\nalbum_name\x18\x03 \x01(\t\"(\n\x10\x44ownloadResponse\x12\x14\n\x0c\x64ownload_url\x18\x01 \x01(\t\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x88\x01\n\x0f\x44ownloadService\x12\x36\n\x0bHealthCheck\x12\x12.grpc.HelloRequest\x1a\x13.grpc.HelloResponse\x12=\n\x0c\x44ownloadSong\x12\x15.grpc.DownloadRequest\x1a\x16.grpc.DownloadResponseB\x06Z\x04.;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'download_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004.;pb'
  _globals['_DOWNLOADREQUEST']._serialized_start=24
  _globals['_DOWNLOADREQUEST']._serialized_end=101
  _globals['_DOWNLOADRESPONSE']._serialized_start=103
  _globals['_DOWNLOADRESPONSE']._serialized_end=143
  _globals['_HELLOREQUEST']._serialized_start=145
  _globals['_HELLOREQUEST']._serialized_end=173
  _globals['_HELLORESPONSE']._serialized_start=175
  _globals['_HELLORESPONSE']._serialized_end=207
  _globals['_DOWNLOADSERVICE']._serialized_start=210
  _globals['_DOWNLOADSERVICE']._serialized_end=346
# @@protoc_insertion_point(module_scope)
