openapi: '3.0.3'
info:
  title: API Title
  description: BeatBus api Spec (draft)
  version: '1.0'
servers:
  - url: http://localhost:8080
tags:
  - name: Rooms
    description: Room related endpoints, Create,Delete rooms, End Rooms, Only the host can interact with these endpoints
  - name: Queue
    description: Queue related endpoints, Manage queue positions, Skip tracks
  - name: Host
    description: Host related endpoints, Only the host can interact with these endpoints
  - name: Metrics
    description: metrics related endpoints, Like/Dislike songs, Get most liked songs of session, send most liked songs to users, send liked songs to users number. Mr.put on user with most liked songs

paths:
  /Rooms/{roomId}:
    get:
      parameters:
        - in: query
          name: roomPassword
          schema:
            type: string
          description: The password for the room, if the room 
      tags:
        - Rooms
      summary: Join a room by ID
      description: Join a specific room using its ID, This is what the user does when they enter a room code on the front end
      responses:
        '200':
          description: Successful Response
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
  /Rooms:
    post:
      tags:
        - Rooms
        - Host
      summary: Create a room
      description: Create a room with settings such as max users, isPublic, allowGuests, and set the room name
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoomCreate'
      responses:
        '201':
          description: Room Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomSuccessfulResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '409':
          description: Conflict - Room with the same name already exists
        '429':
          description: Too many requests - Rate limit exceeded
    put:
      tags:
        - Rooms
        - Host
      summary: Update Room Settings
      description: Update the settings of a room,max users, isPublic, remove guest from your rooms
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoomCreate'
      responses:
        '200':
          description: Room Updated Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomSuccessfulResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
    delete:
      tags:
        - Rooms
        - Host
      summary: Delete a room
      description: Delete a room, only the host can delete the room, kicks everyone out of the room. Returns the user with most liked songs in the session. (Mr put on)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                hostId:
                  type: string
                  description: The ID of the user who is the host of the room.
                roomId:
                  type: string
                  description: The ID of the room to delete.
      responses:
        '200':
          description: Room Deleted Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  MrPutOn:
                    type: string
                    example: richard123
                    description: The ID of the user with the most liked songs in the session.
        '400':
          description: Bad Request
        '401':
          description: Unauthorized

  /Queues/{roomID}/playlist:
    post:
      tags:
        - Queue
      summary: Add a song to the queue
      description: Add a song to the queue, if the song is already in the queue, it will not be added again
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                songName:
                  type: string
                  description: The name of the song to add to the queue.
                artistName:
                  type: string
                  description: The name of the artist of the song to add to the queue.
                addedBy:
                  type: string
                  description: The ID of the user who is adding the song to the queue.
      responses:
        '200':
          description: Song Added Successfully
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
    get:
      tags:
        - Queue
      summary: Get the current queue
      description: Get the current queue of songs in the room
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    song:
                      $ref: '#/components/schemas/SongObject'
                    alreadyPlayed:
                      type: boolean
                      description: Indicates if the song has already been played
                    position:
                      type: integer
                      description: The position of the song in the queue
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
    put:
      tags:
        - Queue
        - Host
      summary: Reorder the queue, (handles skips)
      description: Reorder the queue by providing a new order of song IDs, This is only for the host. This will be heavily related to the front end. front end must keep the queue order and allow only the host to change the visible order and then send that updated version the backend, Only host and the user who added the song to the queue can skip it
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newOrder:
                  type: array
                  items:
                    type: string
                  description: An array of song IDs representing the new order of the queue.
      responses:
        '200':
          description: Queue Reordered Successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    song:
                      $ref: '#/components/schemas/SongObject'
                    alreadyPlayed:
                      type: boolean
                      description: Indicates if the song has already been played
                    position:
                      type: integer
                      description: The position of the song in the queue
        '400':
          description: Bad Request
        '401':
          description: Unauthorized

  /Metrics/{roomID}:
    get:
      tags:
        - Metrics
      summary: Get metrics about the entire session so far
      description: In depth metrics about the entire session so far, most liked songs, most disliked songs, user with most liked songs, user with most disliked songs. generates a report for each song played (who played it, likes and dislikes)
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomMetrics'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
    post:
      tags:
        - Metrics
      summary: Send Like/Dislike for current song
      description: Send a like or dislike for a song, This will update the like/dislike count for the song
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: The ID of the user sending the like/dislike.
                songId:
                  type: string
                  description: The ID of the song being liked/disliked.
                action:
                  type: string
                  enum: [like, dislike]
                  description: 'Specify "like" to like the song or "dislike" to dislike the song.'
      responses:
        '200':
          description: Like/Dislike Sent Successfully
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '429':
          description: Too Many Requests - Rate limit exceeded (dont spam the like/dislike button)

  /Metrics/{roomID}/playlist/send:
    post:
      tags:
        - Metrics
        - Host
      summary: Send playlist to select users in the room
      description: Send the playlist (all songs or only most liked) to select users in the room via email or notification.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                users:
                  type: array
                  items:
                    type: string
                  description: List of user IDs or emails to send the playlist to.
                type:
                  type: string
                  enum: [all, liked]
                whom:
                  type: string
                  enum: [all, stayedToEnd]
                  description: 'Specify "all" for the entire playlist or "liked" for most liked songs.'
      responses:
        '200':
          description: Playlist sent successfully
        '207':
          description: Partial Success - Some users may not have received the playlist (TBD needs more detail for each users as to why it didnt succeed)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: array
                    items:
                      type: string
                    description: List of users who successfully received the playlist.
                  failed:
                    type: array
                    items:
                      type: string
                    description: List of users who did not receive the playlist.
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
  /Metrics/{roomID}/History:
    get:
      tags:
        - Metrics
      summary: Get the history of songs played in the session
      description: Get a detailed history of all songs played in the session, including who added them, likes, dislikes, and timestamps.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SongObject'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:


    RoomCreate:
      type: object
      properties:
        roomName:
          type: string
          description: The name of the room.
        lifeTime:
          type: integer
          description: The lifetime of the room in minutes.
        maxUsers:
          type: integer
          description: The maximum number of users allowed in the room.
        isPublic:
          type: boolean
          description: Indicates if the room is public or private.


    RoomSuccessfulResponse:
      type: object
      properties:
        roomProperties:
          $ref: '#/components/schemas/RoomProperties'
        timeStamp:
          type: string
          format: date-time
          description: The timestamp when the room was created.


    RoomProperties:
      type: object
      properties:
        roomId:
          type: string
          description: The unique identifier for the room.
        roomPassword:
          type: string
          description: The password for the room, users will need this to join if the Room
        hostId:
          type: string
          description: The ID of the user who is the host of the room.
        roomName:
          type: string
          description: The name of the room.
        maxUsers:
          type: integer
          description: The maximum number of users allowed in the room.
        isPublic:
          type: boolean
          description: Indicates if the room is public or private.


    SongStats:
      type: object
      properties:
        title:
          type: string
          description: The title of the song.
        artist:
          type: string
          description: The artist of the song.
        album:
          type: string
          description: The album of the song.
        duration:
          type: integer
          description: The duration of the song in seconds.
      required:
        - title
        - artist


    SongMetadata:
      type: object
      properties:
        addedBy:
          type: string
          description: The ID of the user who added the song to the queue.
        likes:
          type: integer
          description: The number of likes the song has received.
        dislikes:
          type: integer
          description: The number of dislikes the song has received.


    SongObject:
      type: object
      description: Represents a song in the queue with its stats and metadata. logical abstraction since we aren't sure how exactly we are going to represent this yet
      properties:
        songId:
          type: string
          description: The unique identifier for the song. this is for internal use more than anything else
        stats:
          $ref: '#/components/schemas/SongStats' 
        metadata:
          $ref: '#/components/schemas/SongMetadata'


    RoomMetrics:
      type: object
      properties:
        mostLikedSongs:
          type: array
          items:
            $ref: '#/components/schemas/SongMetadata'
          description: List of the most liked songs in the session.
        mostDislikedSongs:
          type: array
          items:
            $ref: '#/components/schemas/SongMetadata'
          description: List of the most disliked songs in the session.
        userWithMostLikes:
          type: string
          description: The ID of the user with the most liked songs.
        userWithMostDislikes:
          type: string
          description: The ID of the user with the most disliked songs.
        roomsize:
          type: integer
          description: The number of users currently in the room.
        queueLength:
          type: integer
          description: The number of songs currently in the queue.
      required:
        - mostLikedSongs
        - mostDislikedSongs
        - userWithMostLikes
        - userWithMostDislikes
        - roomsize
        - queueLength

   